server:
  port: 8070

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3309/product_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: product
    password: product123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
