services:

  # =========================================================
  # KEYCLOAK MYSQL
  # =========================================================

  keycloak-mysql:
    image: mysql:8.4
    container_name: ecom-keycloak-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak123

    ports:
      - "3308:3306"

    volumes:
      - keycloak_mysql_data:/var/lib/mysql

    networks:
      - ecom-network


  # =========================================================
  # KEYCLOAK
  # =========================================================

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: ecom-keycloak
    restart: unless-stopped

    command: start-dev

    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloak-mysql:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123

      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin123

    ports:
      - "8085:8080"

    depends_on:
      - keycloak-mysql

    networks:
      - ecom-network


  # =========================================================
  # KEYCLOAK PHPMYADMIN
  # =========================================================

  keycloak-phpmyadmin:
    image: phpmyadmin:latest
    container_name: ecom-keycloak-phpmyadmin
    restart: unless-stopped

    environment:
      PMA_HOST: keycloak-mysql
      PMA_PORT: 3306

    ports:
      - "8083:80"

    depends_on:
      - keycloak-mysql

    networks:
      - ecom-network


  # =========================================================
  # KAFKA - KRaft
  # =========================================================

  kafka:
    image: apache/kafka:4.1.0
    container_name: ecom-kafka
    restart: unless-stopped

    ports:
      - "9092:9092"

    environment:

      # -----------------------------
      # KRaft
      # -----------------------------

      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093


      # -----------------------------
      # Listeners
      # -----------------------------

      KAFKA_LISTENERS: INTERNAL://:9094,EXTERNAL://:9092,CONTROLLER://:9093

      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9094,EXTERNAL://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER


      # -----------------------------
      # Single broker
      # -----------------------------

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1


      # -----------------------------
      # General
      # -----------------------------

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - kafka_data:/var/lib/kafka/data

    networks:
      - ecom-network


  # =========================================================
  # KAFKA UI
  # =========================================================

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ecom-kafka-ui
    restart: unless-stopped

    ports:
      - "8084:8080"

    depends_on:
      - kafka

    environment:
      KAFKA_CLUSTERS_0_NAME: ecom-kafka

      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094

    networks:
      - ecom-network

  # =========================================================
  # SONARQUBE
  # =========================================================

  sonarqube:
    image: sonarqube:community
    container_name: ecom-sonarqube
    restart: unless-stopped

    ports:
      - "9000:9000"

    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

    networks:
      - ecom-network


# =========================================================
# VOLUMES
# =========================================================

volumes:

  keycloak_mysql_data:

  kafka_data:

  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:


# =========================================================
# NETWORK
# =========================================================

networks:

  ecom-network:
    driver: bridge